# Site settings
url: https://gowebmasters.club
title: Go Web Masters
description: >
  An online community tying together a diverse and passionate group of web technologists from all around the world.

# Build settings
markdown: kramdown

exclude: [scripts]

gems:
  - jekyll-redirect-from
